### ISSUE TITLE
port control interface definition to smithy

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#125]
The types being used by the `wasmcloud-control-interface` crate are currently defined using widl. We need to convert this so that the data types are being generated via smithy (with no services since we don't generate NATS RPC stubs).

**Comment by stevelr** [comment]
first draft of this is in wasmcloud/interfaces/core/wasmcloud-core.smithy
this is not final for the 0.50 release. Some interfaces need review, discussion, and/or clarification.
