### ISSUE TITLE
Support actor invocations from the control interface

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#128]
Actor invocations (previously used by something like `wash ctl call`) should be a part of the control interface in order to directly invoke actor handlers.

**Comment by autodidaddict** [comment]
How would this be different than just using the RPC connection to make regular RPC calls to the actors?

**Comment by brooksmtownsend** [comment]
@autodidaddict It's not different, but putting it in the control interface creates an easy interface for the washboard to make such calls instead of having to manage an invocation struct, generate guids, etc. I was referring mostly to how the old control interface provided a function for calling actors, but the OTP control interface does not https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-control-interface/src/lib.rs#L136

**Comment by autodidaddict** [comment]
I think what really needs to happen here is that `wash` needs to be able to reach for 2 different sets of credentials - one for the RPC connection and one for the CTL connection, and this `call` function should be moved from `ctl` to `rpc`. This whole dual connection thing has been inconsistently handled and I do not want to add RPC invocations to the control interface as that would be exposing functionality to one connection that should be isolated in another.

**Comment by stevelr** [comment]
Brooks, re: needing to make invocation struct. Hostbridge in wasmbus-rpc/provider.rs has a send_actor fn that does all that. I need to refactor it so you can use it outside a provider.

**Comment by autodidaddict** [comment]
@stevelr the `wasmcloud-control-interface` crate also has the creation of invocations, etc. The issue here is mainly that we shouldn't be using the control interface connection/credentials to send RPC calls, that needs to take place on the control connection.

This and other changes are being bundled in [https://github.com/wasmCloud/wash/issues/149](https://github.com/wasmCloud/wash/issues/149)

**Comment by autodidaddict** [comment]
Closing this as a "will not implement" - the control interface cannot be used to invoke actors (or providers) for security reasons. The RPC and control connection separation is essential for security and allowing an RPC bypass via the control interface would violate that separation.
