### ISSUE TITLE
Reduce health check logging verbosity

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#129]
Currently, there are 4 or 5 info level logs per health check that get logged to the OTP stdout. When we get to a high actor count, say 100 replicas of the echo actor (completely attainable and realistic) this adds 4/500 logs every 30s. I think this should be reduced to a debug level log, or at least reduced to 1 successful info log for a passing health check and 1 warn log for a failed health check.

Thoughts @autodidaddict ?

**Comment by autodidaddict** [comment]
Agreed this wasn't designed to stay that spammy there's a lot of info stuff that should be trace.
