### ISSUE TITLE
Actor interface to expose wasmbus-rpc protocol version number

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmcloud-otp#135]
For future-compatibility, actors should expose a wasmbus-rpc version number. In the future, if we ever change invocation apis or the type of message serialization, we can bump the version number. The host would check the version number before doing rpc with the actor, and use the appropriate compatibility shim if necessary. Not trying to be prescriptive of how host implements this - just describing the concept.

I'm going to assign this to Kevin to pick the symbol name, then he can reassign this to me to implement exposing the version from the actor code generation.

**Comment by autodidaddict** [comment]
The host runtime also publishes this version number in the `ActorStarted` event, along with the actor public key.

**Comment by autodidaddict** [comment]
For further detail, all actors pre-0.5 are considered to be on rpc version `0` while 0.5+ is rpc version `1`.
