### ISSUE TITLE
Implement health checks for Providers

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#145]
Our httpserver/wasmcloud-redis providers that are in this repository should implement health checks, and all generated providers from smithy should also implement health checks.

**Comment by stevelr** [comment]
Capability providers implemented in rust using the wasmbus-rpc library implement a trait which has a default health check implementation that always returns healthy. 

There's a separate question of what should a good health check function do to determine whether its service is healthy, which this issue didn't ask. 

We have implemented the ability for capability providers to automatically confirm that they can respond to healthy check queries.

**Comment by brooksmtownsend** [comment]
The important thing is that we have a basic health check mechanism that should indicate if the provider isn't responding, and if it is responding then we get some amount of certainty that it's at least _running_. Glad it's automatically implemented on the Trait, can it be overridden?
