### ISSUE TITLE
Store provider claims in claims_table

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#153]
Stems from #152 

Currently, only the actor claims are stored in the ets claims_table. We should also store provider claims in the table as well so we can retrieve relevant information like revision, version, etc later on in the host run process.

The "bug" in this issue is that the revision will always be returned as 0 for providers when queried by the control interface, but it's only used for the host inventory query.

**Comment by autodidaddict** [comment]
This was implemented in PR #160. Closing.
