### ISSUE TITLE
Query lattice for running resources and caches on dashboard startup

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#166]
Currently, when the wasmcloud dashboard starts it appears to be blank regardless of running actors, providers, or published link definitions.

We'll need to implement two things:
1. Create hook for cache_loader to advertise events
2. Query running hosts, actors, providers already running on the lattice

Could you add a snippet about the cache_loader hook @autodidaddict ? Want to make sure it's documented well for when we come back here later

**Comment by autodidaddict** [comment]
Created #167 for the cache loader hook.
