### ISSUE TITLE
OCI reference invalid if Actor Key to OCI ref is a one-to-many relationship

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#168]
The current code to look up an oci reference is as follows:
```
  def get_image_ref(pk) do
    case find_oci_for_pk(pk) do
      [[oci]] -> oci
      _ -> nil
    end
  end
```

This works well for when you start an actor from a remote registry. That actor's public key is correlated with the ocireference. However, in the case where more than OCI reference corresponds to the same public key, the `[[oci]]` statement will not match. See an example below for the echo actor:

```
(code)   :ets.match(:refmap_table, {:"$1", "MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5"})
(result) [["wasmcloud.azurecr.io/echo:0.2.0"], ["wasmcloud.azurecr.io/echo:0.2.1"]]
```

This will instead return `nil`. At the moment elixir `ActorModule` modules _do_ have access to their own oci reference, so we should instead interrogate the `ActorModule` for its OCI reference rather than looking it up in the ets cache.

**Comment by autodidaddict** [comment]
I think the behavior we want here is to only ever store one OCI reference for a given public key. When we put an OCI reference into the cache, it should over-write the previously existing reference if there was one. When we live update an actor, we replace all instances with the new version, so the "old" OCI reference is no longer valid at that point.

**Comment by brooksmtownsend** [comment]
@autodidaddict What about the scenario where I have a running echo actor from both oci references? This might not be a desired outcome ATM, but feasibly this could be a scenario that we support with canary deployments, etc. This was actually how I discovered the bug, by starting an actor from `echo:0.2.0` and `echo:0.2.1`

**Comment by autodidaddict** [comment]
We shouldn't be able to run two different versions of the same actor in the same host. At least that's how I've been assuming since the beginning.
