### ISSUE TITLE
Add OPA support

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#17]
Rather than building a totally generic authorization system, allow people to optionally use Open Policy Agent by providing an OPA policy execution URL and optional username and password for that URL. The policy will be sent the actor JWT claims and some other information (which we will specify/document) and then the "can it make this call" decision will be deferred to the OPA policy.

**Comment by brooksmtownsend** [comment]
It appears we're going to go with the generic authorization system after all, #439, with the option of adding OPA in the future as the policy API matures
