### ISSUE TITLE
no log output when actor invokes logging provider

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmcloud-otp#173]
This is my first attempt to use the builtin logging provider, so it could be a bug in the actor or the otp host.
When I invoke WriteLog, I see debug messages from the host:

```
[debug] Guest request
[debug] Got current invocation
[debug] host call: wasmcloud:builtin:logging - default: WriteLog (25 bytes)
[debug] host call: wasmcloud:builtin:logging - default: WriteLog (28 bytes)
[debug] host call: wasmcloud:builtin:logging - default: WriteLog (32 bytes)
[debug] host call: wasmcloud:builtin:logging - default: WriteLog (58 bytes)
```
The actor wasm is signed with the capability "wasmcloud:builtin:logging", which I confirmed with `wash claims inspect`.

I tried invoking Linkdefs.Manager.put_link_definition to bind the actor to the logging interface, but that produces the error: 

```
Invalid provider spec: no provider with contract wasmcloud:builtin:logging
```

Is it possible that the host isn't performing the linking to builtin providers when the actor is started, or that the host doesn't know that the builtin providers are available?

other details:
WriteLog invokes __host_call, as it does for other providers, with "wasmcloud:builtin:logger" and "default".

The message is a messagepack structure containing "level" and "text", both strings, which looks like the structure that is being used in logger.ex.

**Comment by stevelr** [comment]
Here's additional information. I wasn't logging the error returned:
```
 Host send error Invocation not authorized
 ```

I just tried an actor with the numbergen builtin provider and got back the same error, even though the actor is signed with the capability.

**Comment by autodidaddict** [comment]
Builtins don't require link defs in otp. Will investigate the rest.

**Comment by autodidaddict** [comment]
Your own comment says you're invoking wasmcloud:builtin:logger but the contract I'd is logging,  not logger. Was that a typo in the issue?

**Comment by autodidaddict** [comment]
Looks like this is coming from logic that denies authorization to all invocations that don't have a corresponding linkdef, and builtins don't require linkdefs in the OTP version. Will have a PR to fix this shortly.

**Comment by stevelr** [comment]
tested on "bugs/nobuiltins" branch
