### ISSUE TITLE
bugs in random numbergen

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmcloud-otp#174]
In numbergen.ex:
```
def invoke("RandomInRange", payload) do
    params = Msgpax.unpack!(payload)

    min = min(params["min"], 0)
    max = max(params["max"], 4_294_967_295)
    Msgpax.pack!(Enum.random(min..max))
end
```

min() should be max(), and max() should be min()
and the upper bound is defined (in the smithy interface) to be exclusive, but Enum.random range is inclusive, so, I think the implementation should be like this:
```
def invoke("RandomInRange", payload) do
    params = Msgpax.unpack!(payload)

    min = max(params["min"], 0)
    max = min(params["max"]-1, 4_294_967_295)
    Msgpax.pack!(Enum.random(min..max))
end
```
Also, bug(s) here:

```
 def invoke("Random32", _payload) do
    Msgpax.pack!(floor(:rand.uniform(4_294_967_294)))
  end
```

rand.uniform returns a number from 1<=n<=max, and it's an int so I don't know why you need floor().  I think this function should be

```
 def invoke("Random32", _payload) do
    Msgpax.pack!(:rand.uniform(4_294_967_296)-1)
  end
```
or `Enum.random(0..4_294_967_295)` but I don't know the tradeoffs between Enum.random and :rand.uniform.

**Comment by autodidaddict** [comment]
Woopsy on the use of `floor`, I must've been reading the docs for `uniform/0`, which returns a float, whereas `uniform/1` returns an int.
