### ISSUE TITLE
Dashboard does not accurately reflect health information for actor pools

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#180]
The dashboard does not accurately represent health information for actors that have more than one instance.

For actors that have multiple instances, the displayed health status is simply the most recent one received. In most cases this is accurate, however if there are 100 instances of an actor and 99 of them are unhealthy, it will still show `Healthy` when the healthy actor responds to the health check.

This can be solved by changing the stored actor data to include the instance ID, and then display an aggregate health result (e.g. show unhealthy if _any_ actor with that public key is unhealthy). We may also want to consider allowing the user to expand an actor pool to individually inspect actor status

**Comment by stevelr** [comment]
post mvp - we're not sure if this is a likely scenario

**Comment by brooksmtownsend** [comment]
No longer applicable as actor health isn't shown in the dashboard (due to how unreliable it is as a metric)
