### ISSUE TITLE
Support remote (detached) capability providers

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#19]
Support the ability to "start" a capability provider that is already sitting on the appropriate lattice topics. Such a provider would not be able to be terminated, but would still receive all appropriate messages about creation and removal of link definitions. (remember that link def assignment is no longer an invocation, providers must subscribe to the `.claims.put` topic.

**Comment by stevelr** [comment]
removing this from OTP-MVP epic

**Comment by autodidaddict** [comment]
Not implementing this.
