### ISSUE TITLE
Issue handling actor heartbeats

### ISSUE THREAD

**Issue by based-template** [wasmCloud/wasmcloud-otp#215]
I'm getting the following output when starting actors, indicating that heartbeats are not being processed/handled correctly (?)

I am not seeing the same issue running providers, where it seems that the heartbeats are handled correctly 

This is for the wasmcloud.azurecr.io/echo:0.3.1 actor, I've seen the same issue with other actors (a rebuild 'hello' actor updated to current interfaces)

`[info] Starting actor
[info] Actor module starting
[debug] Cached claims for MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5
[info] Subscribing to wasmbus.rpc.default.MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5
[debug] Publishing ref map
[debug] Cached OCI map reference from wasmcloud.azurecr.io/echo:0.3.1 to MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5
[info] StateMonitor handle info wasmbus.evt.default
[debug] Publishing heartbeat
[info] StateMonitor handle info wasmbus.evt.default
[info] Handling host heartbeat
[info] performing invocation HealthRequest
[info] Agent state updated
[debug] Guest request
[debug] Got current invocation
[debug] Guest error
[info] OK result
[info] StateMonitor handle info wasmbus.evt.default
[info] Handling failed health check for MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5
[debug] Publishing heartbeat
[info] StateMonitor handle info wasmbus.evt.default
[info] Handling host heartbeat
[info] performing invocation HealthRequest
[info] Agent state updated
[debug] Guest request
[debug] Got current invocation
[debug] Guest error
[info] OK result
[info] StateMonitor handle info wasmbus.evt.default
[info] Handling failed health check for MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5`

This is when running wasmcloud-otp off commit aef10f2f07257e65c527be6030006aaed2b85ff9 (most current on main)

**Comment by brooksmtownsend** [comment]
@stevelr tagging you here as this looks like it might relate to the codegen actor health check

**Comment by stevelr** [comment]
I think the fix is to change 

 @op_health_check "HealthRequest"

In actor_module.ex to 

 @op_health_check "Actor.HealthRequest"

I'll test this tomorrow.

**Comment by autodidaddict** [comment]
This has been changed in the PR I'm working on for invocation validation, and as such will be fixed when that gets merged.

**Comment by brooksmtownsend** [comment]
This was fixed in #216
