### ISSUE TITLE
Allow host to start before NATS

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#22]
In an effort to keep things as simple and easy and _error-free_ as possible, we'd like to be able to start the host even if NATS isn't running. The host would essentially sit in an idle, non-functional, "not ready" state until it detects that NATS is available. Once NATS is available, it'll connect, make all its subscriptions, enable functionality, and put itself in the "ready" state.

**Comment by autodidaddict** [comment]
SITREP: After spending basically the entire morning pairing on this, we discovered a number of things. The first is that it's really tricky and difficult and actually quite un-idiomatic to hold up/slow down/block the supervision hierarchy startup sequence in order to establish a connection to a NATS broker (or database or whatever).

Secondly, after consulting with someone who actually knows what they're doing, we came across the [ConsumerSupervisor](https://hexdocs.pm/gnat/Gnat.ConsumerSupervisor.html), which looks like it's a way to manage/maintain subscriptions in a connection-independent manner. This should, in theory, let us maintain our subscriptions across client restarts (network partition events).

There are also some issues with the code and complexity in the Gnat client that we may want to file as issues with the NATS client team.

**Comment by autodidaddict** [comment]
Since we have two connections (one for RPC and one for the control interface), we could create 2 [Gnat.Server](https://hexdocs.pm/gnat/Gnat.Server.html#content)s that handle the messages they need to handle from those topics, managed by a single `ConsumerSupervisor`.

We're currently putting this issue near the bottom of the backlog so we can get more mission-critical functionality out of the way. This will give us some time to stew on the most idiomatic (and hopefully simple) solution to this problem.

**Comment by QuinnWilton** [comment]
Based on what we chatted about, I think the `ConsummerSupervisor` is likely what you want. Note that you'll also need to use the [ConnectionSupervisor](https://hexdocs.pm/gnat/Gnat.ConnectionSupervisor.html) in your supervision tree, in order to manage the connection.

**Comment by QuinnWilton** [comment]
For what it's worth, I noticed [this](https://github.com/nats-io/nats.ex/issues/62) issue in the `GNat` tracker, so it sounds like they're aware of some of the issues surrounding the connection handling not being super idiomatic. A lot of the suggestions and concerns brought up by others in that thread align with the issues I pointed out to you.
