### ISSUE TITLE
[BUG] Provider start can occasionally show error in phoenix logs

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#236]
Error logs below (thanks @ks2211 )
```
[error] GenServer #PID<0.737.0> terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(2, nil)
    (wasmcloud_host 0.50.0) lib/wasmcloud_host_web/live/page_live.html.leex:127: anonymous fn/4 in WasmcloudHostWeb.PageLive.render/1
    (stdlib 3.16) maps.erl:410: :maps.fold_1/3
    (wasmcloud_host 0.50.0) lib/wasmcloud_host_web/live/page_live.html.leex:126: anonymous fn/3 in WasmcloudHostWeb.PageLive.render/1
    (stdlib 3.16) maps.erl:410: :maps.fold_1/3
    (wasmcloud_host 0.50.0) lib/wasmcloud_host_web/live/page_live.html.leex:125: anonymous fn/2 in WasmcloudHostWeb.PageLive.render/1
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:130: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:723: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:596: Phoenix.LiveView.Channel.handle_changed/4
    (stdlib 3.16) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Looks like this doesn't affect the ability to start a provider, but it shows regardless. Looking at those lines of code it's likely just that the provider starts just slightly before its claims are present in the claims list on the UI side, so it fails to find the provider. We should be able to change the logic for the pipe to safely handle this scenario

**Comment by brooksmtownsend** [comment]
This was fixed by #250

**Comment by alanpoon** [comment]
Hi, I still got this error.
[error] #PID<0.749.0> running WasmcloudHostWeb.Endpoint (connection #PID<0.723.0>, stream id 4) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

        :erlang.element(2, nil)
        (wasmcloud_host 0.50.1) lib/wasmcloud_host_web/live/page_live.html.heex:127: anonymous fn/4 in WasmcloudHostWeb.PageLive.render/1
        (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
        (wasmcloud_host 0.50.1) lib/wasmcloud_host_web/live/page_live.html.heex:126: anonymous fn/3 in WasmcloudHostWeb.PageLive.render/1
        (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
        (wasmcloud_host 0.50.1) lib/wasmcloud_host_web/live/page_live.html.heex:125: anonymous fn/2 in WasmcloudHostWeb.PageLive.render/1
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
        (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:130: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/static.ex:234: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/static.ex:126: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.6.0) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (wasmcloud_host 0.50.1) lib/wasmcloud_host_web/endpoint.ex:1: WasmcloudHostWeb.Endpoint.plug_builder_call/2
        (wasmcloud_host 0.50.1) lib/plug/debugger.ex:132: WasmcloudHostWeb.Endpoint."call (overridable 3)"/2
        (wasmcloud_host 0.50.1) lib/wasmcloud_host_web/endpoint.ex:1: WasmcloudHostWeb.Endpoint.call/2
        (phoenix 1.6.0) lib/phoenix/endpoint/cowboy2_handler.ex:43: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /Users/alan.poon/Documents/rust/wascc/wasmcloud-otp/wasmcloud_host/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2

**Comment by brooksmtownsend** [comment]
@alanpoon did you get this error using the tarball release, or did you get it with the latest stuff in main? I thought I fixed this but I'll re-open it while we investigate.

If you ran wasmcloud_host with `mix`, what got you this error?

**Comment by alanpoon** [comment]
I ran with mix on commit 2dc0a37c, got this error while uploading a capability provider in the web_ui. Now I am using the tag v0.50.1. 

Running on macos.

**Comment by brooksmtownsend** [comment]
I found the source of this and will publish a PR in a few minutes to solve it
