### ISSUE TITLE
Capability providers can be orphaned

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#258]
Currently, when a host is stopped all actors are also stopped, but capability providers may remain running. These orphaned providers may take up system resources like CPU/memory and they may even hold port listeners or file handlers.

This is most likely to happen by force killing (CTRL+cc) a host in development mode, but can also happen with the release tarball. Barring a kill pid command, we should be able to ensure a host cleans up its resources when told to stop.

**Comment by autodidaddict** [comment]
When `HostCore.Host.purge` is called, the capability providers are given the chance to gracefully shut down and this gives the highest chance of not orphaning the child processes. Otherwise, this is a really difficult one because we don't have much control over what happens when the host is aborted via ctrl-C, etc.

**Comment by brooksmtownsend** [comment]
@autodidaddict I think the appropriate way to handle this issue is probably just to implement [Application.prep_stop/1](https://hexdocs.pm/elixir/1.12/Application.html#c:prep_stop/1) or [Application.stop/1](https://hexdocs.pm/elixir/1.12/Application.html#c:stop/1) and call `HostCore.Host.purge` to gracefully shutdown. If a developer `ctrl+cc`'es then we can't do much, but hopefully the above would solve something like `./bin/wasmcloud_host stop`

**Comment by brooksmtownsend** [comment]
Currently we do handle `./bin/wasmcloud_host stop` gracefully by shutting down providers, and unfortunately (with a lot of research when implementing `wash up`) there's not a graceful way to handle a CTRL+c without trapping OS signals.
