### ISSUE TITLE
Perform first health checks immediately

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#263]
Rather than waiting the health check timeout to perform a health check on something that has been loaded, we should perform that health check immediately. This gives lattice monitors immediate feedback as to whether something was loaded but is unhealthy versus healthy.

**Comment by autodidaddict** [comment]
This should apply to starting actors and starting capability providers.

**Comment by brooksmtownsend** [comment]
To give you an idea of where this is taking place, when we start an Actor we call [Process.send_after/4](https://hexdocs.pm/elixir/1.12/Process.html#send_after/4) to send a health request after thirty seconds (this is taking place [here](https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/actors/actor_module.ex#L236)).

Instead, we should probably be directly using [Process.send/3](https://hexdocs.pm/elixir/1.12/Process.html#send/3) at the end of the [prepare_module](https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/actors/actor_module.ex#L307) function to invoke the health request right away.
