### ISSUE TITLE
Update `handle_request` functions in control interface to handle JSON parse errors

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmcloud-otp#265]
Currently most of the `handle_request` methods in `./host_core/lib/host_core/control_interface/server.ex` do not handle JSON parsing errors gratefully. This can be added by wrapping in a case block like what is done with the stop host command:

```elixir
defp handle_request({"cmd", _host_id, "stop"}, body, _reply_to) do
    case Jason.decode(body) do
      {:ok, _stop_host_command} ->
        Logger.info("Received stop request for host")
        HostCore.Host.purge()
        publish_host_stopped()
        # Give a little bit of time for the event to get sent before shutting down
        :timer.sleep(100)

        :init.stop()

      {:error, e} ->
        Logger.error("Unable to parse incoming stop request: #{e}")
        failure_ack("Unable to perform stop host command: #{e}")
    end
  end

**Comment by brooksmtownsend** [comment]
I ran into this when starting #290, specifically when trying to run `wash ctl get inventory`. Looks like the lattice control client changed the expected payload, I noted that [ActorDescription](https://docs.rs/wasmcloud-interface-lattice-control/0.2.1/wasmcloud_interface_lattice_control/struct.ActorDescription.html) expects a list of instances but the host runtime just returns an instance_id atm.
