### ISSUE TITLE
phoenix_live_view__WEBPACK_IMPORTED_MODULE_4__.LiveSocket is not a constructor

### ISSUE THREAD

**Issue by alanpoon** [wasmCloud/wasmcloud-otp#272]
commit: 2d65fe8
![image](https://user-images.githubusercontent.com/8205468/141334421-4292ad0a-eff6-41ea-9c33-44276e260b84.png)

**Comment by brooksmtownsend** [comment]
@alanpoon this looks like something that I've gotten when I've forgotten to run `npm install` in the `assets` directory, or that the `npm install` failed instead of completing successfully
