### ISSUE TITLE
Monitor cloud events

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#29]
Related to #6 

We publish CloudEvents for things like `provider_started`, `actor_started`, `provider_stopped`, and more after the above issue. We should have a module that can be instantiated and monitor for these types of events, similar to what was implemented in https://github.com/wasmCloud/wasmCloud/pull/183.

The goal of such a module would be to provide a way to monitor events that occur in a wasmcloud host / lattice, which could either be used to replay events leading up to an issue or assert that specific events had occurred. For example, when we write tests that start a provider, we can ensure that the provider has had enough time to spawn as a process and is ready for invocations.

**Comment by stevelr** [comment]
taken care of by other issues
