### ISSUE TITLE
[FEATURE] Allow UnknownImport in starting actor

### ISSUE THREAD

**Issue by alanpoon** [wasmCloud/wasmcloud-otp#324]
There's import error while starting actor.
![image](https://user-images.githubusercontent.com/8205468/147629276-9dbde9ec-e306-4e49-b772-536c85544d82.png)
I don't have this error in rust version of wasmcloud_host.

I maybe use dependences that uses wasmbindgen in compiling my Actors. But the functions I used may not eventually calls wasmbindgen functions.

**Comment by autodidaddict** [comment]
Actors are not compatible with wasm bindgen. Bindgen creates rust code that relies on the server to have certain imports available, like those exposed by the bindgen JavaScript shim. 

Actors get their capability from capability providers and cannot use bindgen.

**Comment by autodidaddict** [comment]
If the bindgen function isn't used then it should be removed by post process cleanup of the wasm file before being signed by wash.

**Comment by alanpoon** [comment]
I am using https://github.com/rustwasm/wasm-snip, it works by snipping out "bindgen" functions

**Comment by autodidaddict** [comment]
If snipping out the bindgen functions works then it should work just fine with the runtime. Actors should only ever import the requirements from the wasmbus protocol
