### ISSUE TITLE
[BUG] Provider RPC happens over the incorrect NATS connection

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#336]
**Describe the bug**

This bug only applies when the capability provider NATS connection is separate from the lattice NATS connection. As you can see in the `perform_rpc_invoke` function here https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/web_assembly/imports.ex#L390-L398, the request goes over the `:lattice_nats` Gnat connection. We should be using a separate Gnat connection, perhaps called `:provider_nats`, in order to make this RPC.

**Comment by autodidaddict** [comment]
So here's an interesting fun fact, the RPC connection _is_ called `:lattice_nats`, as you can see where we initialize the RPC connection:

https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/nats.ex#L8

**Comment by brooksmtownsend** [comment]
Just commenting after our discussion; that is correct, we also have a provider RPC connection which is separate from the lattice RPC connection. When these two connections are separate we will likely see some bugs with communicating with providers.

As discussed, it would be worth our time to do an audit of our three NATS connections (lattice RPC, control interface, provider RPC)

Here's where the provider NATS connection information is generated for the provider https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/host.ex#L230-L231
