### ISSUE TITLE
Host should supply host data and other configuration metadata to spawned capability provider

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#36]
In the current experiment, the capability provider is launched with no information. It doesn't know the host ID, doesn't know how to connect to nats, doesn't know anything. I propose that a `HostData` JSON structure be passed to the capability provider as an environment variable called `WASMCLOUD_HOST_DATA` and it have the following structure:

```json
{
    "host_id": "Nxxxxx",
    "lattice_rpc_user_jwt":  "ed2xxxxx.xxxx",
    "lattice_rpc_user_seed": "Sxxxxx",
    "lattice_rpc_url" : "nats://0.0.0.0:4222",
    "provider_key": "Vxxxxxx",
}
```
The fields are as follows:

* `host_id` - The public key of the host, in the "node" prefix form `Nxxxx`
* `lattice_rpc_user_jwt` - A User JWT to be used for connecting to NATS. This JWT will be _minted by the host_ if the host has been provided a suitable account seed. Otherwise, this will be empty and anonymous authentication will be assumed.
* `lattice_rpc_user_seed` - A user seed required to authenticate against NATS. User credentials for RPC NATS are minted by the host if the host has been provided an account seed. Otherwise, this will be empty and anonymous authentication is assumed.
* `lattice_rpc_url` - The URL of the NATS host for the provider to connect in order to establish connectivity to the lattice
* `provider_key` - The provider's public key. The rest of the claims are not needed for this provider to do its job, and so it is only given the public key, which is used when generating `Invocation`s to be sent to actors within the lattice.

**Comment by autodidaddict** [comment]
Note that if we do end up supporting external/remote capability providers (providers not spawned as a child process by the host, those that already run of their own accord), we don't need to provide them with a host data structure, because their presence in the lattice is determined by discovery of their first heartbeat. In other words, they already know how to get on the lattice and they already know who they are.

**Comment by autodidaddict** [comment]
But your other point is spot on - the credentials are minted and controlled by the host, so the host can invalidate them at any time by making the appropriate NATS call if it wants.

**Comment by autodidaddict** [comment]
# Arbitrary Environment Variables

It looks like I completely forgot that the new wasmCloud host runtime is a daemon process that isn't supposed to have an environment. It doesn't start and stop at the command line, it should start when the server starts and stop when the server stops. This rules out using the host itself as an environment proxy. Earlier I was thinking that we could simply use some kind of prefix code on the environment variables used to start the host runtime, strip the prefix off and add those values to the `WASMCLOUD_HOST_DATA` JSON structure. This is not physically possible.

## Solution

In order to get arbitrary variables into the child provider executable's environment, we'll need to get those variables from the _control interface_, and allow them to be passed as optional values when using the corresponding Elixir API (the control interface listener will invoke the Elixir API, just like the old listener invoked the Rust API). I propose that we add a new `env_values` field to the control interface structure that is an `Option<HashMap<String, String>>` for backwards compatibility. If this structure is there, then the newly started capability provider will get a `WASMCLOUD_HOST_DATA` JSON structure that looks like this:

```json
{
    "host_id": "Nxxxxx",
    "lattice_rpc_user_jwt":  "ed2xxxxx.xxxx",
    "lattice_rpc_user_seed": "Sxxxxx",
    "lattice_rpc_url" : "nats://0.0.0.0:4222",
    "provider_key": "Vxxxxxx",
    "env_values": {
         "variable_name": "foo",
         "variable_2": "bar",
    }
}
```
All of the values passed will have the key (variable name) lowercased and non-alphanumeric characters will be replaced with underscores, e.g. `TONS:OF:FUN` becomes `tons_of_fun`, etc.

This also prevents the security risk of allowing one provider to see another provider's environment through shared environment variables or other env proxy tricks.

**Comment by brooksmtownsend** [comment]
Does this idea close #18 because it's no longer relevant?
