### ISSUE TITLE
[BUG] Dashboard values cannot handle base64 config

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#369]
**Describe the bug**

wasmCloud providers generally support the `config_b64` link definition values, e.g. `config_64=aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1kUXc0dzlXZ1hjUQ==`, however our link definition values are separated by an `=` delimiter in the UI.

Here is our logic for parsing link definitions: https://github.com/wasmCloud/wasmcloud-otp/blob/main/wasmcloud_host/lib/wasmcloud_host_web/live/components/define_link_component.ex#L32-L38. As you can see we are splitting the string by an `=` sign and chunking every 2, which will break for the trailing `=` symbols that commonly follow base64 encoded strings. Our logic in that component needs to be updated to handle this case.

**Comment by emattiza** [comment]
I'll take a stab at this one given i worked on the same issue in [wasmcloud/wash#249](https://github.com/wasmCloud/wash/issues/249)

**Comment by emattiza** [comment]
> I'll take a stab at this one given i worked on the same issue in [wasmcloud/wash#249](https://github.com/wasmCloud/wash/issues/249)

Free to close. Thanks team!
