### ISSUE TITLE
[BUG] Control Interface server is single-threaded blocking

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#376]
**Describe the bug**

The control interface server that listens on the control interface NATS topic is both single-threaded and blocking. While it might ack early to free up consumers, the control interface can block a host.

**To Reproduce**

1. Start a fresh host.
1. Ensure that you have cleaned all the binary caches (`wash drain all`)
1. Issue a `wash ctl start provider` command to load a large provider (the HTTP server one should be fine)
1. Immediately issue a `wash ctl get hosts` and you'll see that no hosts reply within the timeout period (because the host is busy/blocked on the provider start)

**Expected behavior**

The host should remain responsive to all control interface commands and other interaction requests even while performing long-running tasks like a PAR download.

This issue is related to / overlaps with #322

**Comment by brooksmtownsend** [comment]
Tried to reproduce and I can't, so this is fixed 🪨
