### ISSUE TITLE
[BUG] Host doesn't properly handle duplicate capability providers

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#385]
There are two scenarios that need to be accounted for:

* Do not respond positively to provider auctions when the provider ref + link name being auctioned is already running on that host. This is already marked as a `TODO` in the code.
* Gracefully handle control interface requests to start an already running provider (must match link name and key) by emitting a warn log but not crashing. Right now attempting to start the same provider on the host will actually attempt to run that provider twice.

**Comment by brooksmtownsend** [comment]
Closed by #386
