### ISSUE TITLE
[FEATURE] Suppress Heartbeat Logging

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wasmcloud-otp#414]
**Is your feature request related to a problem? Please describe.**
Would it be possible to suppress or minimize the heartbeat log without suppressing other debug logging.

```
16:19:23.152 [debug] Publishing heartbeat
```

**Describe the solution you'd like**
Maybe just log change in heartbeat status

**Additional context**
This log makes up a high percentage of my logging ATM and I would just like to minimize if possible

**Comment by autodidaddict** [comment]
Elixir doesn't have trace level
