### ISSUE TITLE
Replace manual subscriptions with Consumer Supervisors (actors)

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#416]
Today actors subscribe to their RPC topic manually, e.g. `{:ok, subscription} = Gnat.sub(:lattice_nats, self(), topic, queue_group: topic)`. This is fine in testing, but if that subscription were to die or become unstable, there's nothing to fix it. By switching to a consumer supervisor, the subscription can be maintained more durably.

**Comment by brooksmtownsend** [comment]
This has been done for a while! :D
