### ISSUE TITLE
Address Credo and Dialyzer warnings

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#42]
The Github action we currently use to build `host_core` allows failures with the Credo step and the Dialyzer step, in order to let us cache results and continue with our builds and tests. We should resolve all of these failing issues to create a solid baseline for this repository, once we're out of the rapid prototyping phase (e.g. when a TODO: can trigger a failure in the build pipeline).

As a part of this, we should also uncomment the additional elixir versions in the build action so we test across a variety of environments.

**Comment by brooksmtownsend** [comment]
Marking this as `good first issue` as this is a great place to contribute small but very impactful fixes to the host runtime. There are many places where we are getting warnings from credo/dialyzer, and if anyone has basic elixir experience and wants to implement some of these fixes it would be helpful. We'd happily accept a PR that addresses a subset of the warnings.

**Comment by brooksmtownsend** [comment]
We did this! Check out that sweet chain of PRs from @giusdp

**Comment by giusdp** [comment]
woohoo! Now don't let new warning pile up again :D
