### ISSUE TITLE
[BUG] Cannot communicate with actors after stopping all instances

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmcloud-otp#430]
**Describe the bug**

When the last instance of an actor is stopped, the actor's RPC supervisor is terminated. There's a bug in the logic to start actor RPC supervisors that prevents starting one that used to exist

**To Reproduce**

1. Start one or more copies of the echo actor
2. Notice you can successfully invoke the actor 
3. Terminate all instances of the actor
4. Notice you can't invoke the actor (because it's not running) 
5. Start the echo actor again
6. **Notice you _still_ can't invoke the actor**

**Expected behavior**

RPC supervisors should gracefully restart when an actor is restarted

**Comment by brooksmtownsend** [comment]
Closed with #429
