### ISSUE TITLE
[BUG] The button using to copy actor id in the dashboard UI does not work as expected

### ISSUE THREAD

**Issue by Taction** [wasmCloud/wasmcloud-otp#435]
**Describe the bug**

The button to copy actor id in the dashboard UI does not work as expected. Click on it don't copy the actor id to the clipboard. The same issue appears on the providers' button.

**To Reproduce**

N/A

**Expected behavior**

Actor ID should be copied to the clipboard.

**Environment (please complete the following information)**
 - OS: Linux
 - Arch: x86_64
 - wasmCloud Version: main branch build form source.

If you ran into this issue while developing a feature for wasmCloud:
 - Output of `elixir --version` e.g.:
 ```
Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.13.0 (compiled with Erlang/OTP 24)
 ```
 - Output of `cargo --version` e.g.:
 ```
cargo 1.62.0 (a748cf5a3 2022-06-08)
 ```

**Screenshots**

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/13532065/179692093-a2e754e5-68a3-401f-a48e-dd3d8b126d62.png">

**Comment by brooksmtownsend** [comment]
@Taction I can't reproduce this from `main`, just to be sure, did you run `make esbuild` to bundle the javascript?

**Comment by Taction** [comment]
@brooksmtownsend thanks! I deleted the _build folder and then run `make esbuild` 、`make run`, and it disappears.
