### ISSUE TITLE
[BUG] local server gets into bad state and cannot launch actor

### ISSUE THREAD

**Issue by gmlewis** [wasmCloud/wasmcloud-otp#436]
**Describe the bug**

I was following the steps here: https://wasmcloud.dev/app-dev/create-actor/update/
but my project is based on TinyGo so I made the following modifications:

```go
package main

import (
	"fmt"
	"net/url"

	"github.com/wasmcloud/actor-tinygo"
	httpserver "github.com/wasmcloud/interfaces/httpserver/tinygo"
)

func main() {
	me := EchoTinygo{}
	actor.RegisterHandlers(httpserver.HttpServerHandler(&me))
}

type EchoTinygo struct{}

func (e *EchoTinygo) HandleRequest(ctx *actor.Context, req httpserver.HttpRequest) (*httpserver.HttpResponse, error) {
	m, err := url.ParseQuery(req.QueryString)
	if err != nil {
		return nil, fmt.Errorf("url.ParseQuery: %w", err)
	}

	name := "World"
	if n := m.Get("name"); n != "" {
		name = n
	}

	r := httpserver.HttpResponse{
		StatusCode: 200,
		Header:     make(httpserver.HeaderMap, 0),
		Body:       []byte(fmt.Sprintf("Hello %v", name)),
	}
	return &r, nil
}
```

Hot Reload was all set up and I ran "make" which successfully compiled the new version.
When I then ran `curl localhost:8087`, it still gave the old "hello" response.
I killed the actor and tried to restarted it, first using Hot Reload, and then without it.
Now I can't get it to start the actor at all.

**To Reproduce**

1. Set up nats-server and wasmcloud foreground like normal.
2. Create a TinyGo project and launch it with Hot Reload
3. Modify the source, and type "make" again.
4. Try to `curl` and the old version is still being served
5. Scale the existing actor instance to zero.
6. Try to launch a new actor - it refuses.

The logs from elixir show errors... see attached screenshot below.

**Expected behavior**

I expected Hot Reload to work and I expected to be able to re-launch an actor. Both failed.

**Environment (please complete the following information)**
 - OS: Linux
 - Arch: x86_64
 - wasmCloud Version: (how is this determined?)
 - wash version: 0.11.0

**Screenshots**

![ksnip_20220719-144519](https://user-images.githubusercontent.com/6598971/179825721-88d59d42-d8c6-4794-9812-c26fd20f0cc2.png)

**Comment by brooksmtownsend** [comment]
This, unfortunately, is a limitation of TinyGo at this time for the wasm32 freestanding target. If you check out some of the failure messages, like
<img width="713" alt="image" src="https://user-images.githubusercontent.com/12040685/179827729-84a66822-c6ed-4a31-8ba7-ebac375a5ffe.png">

The host is failing to start the actor because it expects the `runtime.ticks` import. Many TinyGo projects have this issue, notably the `"fmt"` package which is used all over the place in Goland 😢 

@jordan-rash Has used TinyGo for a good bit inside of wasmCloud and may have some guidance to help what you're trying to do, and our [kvcounter-tinygo](https://github.com/wasmCloud/examples/blob/main/actor/kvcounter-tinygo/kvcounter_tinygo.go) example may give you a stepping stone to do some parsing without bringing in extra imports

**Comment by jordan-rash** [comment]
Agree with @brooksmtownsend here.  I was able to get alot of these examples working, BUT is required me to edit the underlying Go libraries (Go core) that were being used.  So, what I did, I cant really recommend.

**Comment by jordan-rash** [comment]
What i can recommend, is that if you go install [wasm-dump](https://github.com/WebAssembly/wabt/releases/tag/1.0.29), you can view the exports without having to run the .wasm file -> `wasm-objdump -x derp.wasm`

This saves a lit of time in the feedback loop

**Comment by gmlewis** [comment]
Thank you, @brooksmtownsend and @jordan-rash !
Closing as resolved.

**Comment by gmlewis** [comment]
One other thought on this one... it would be great if the "make" step showed the error instead of making it look like everything was good to go:

```
$ make
tinygo build -o build/echo_tinygo.wasm -target wasm -scheduler none -no-debug .
wash claims sign build/echo_tinygo.wasm --destination build/echo_tinygo_s.wasm --name echo-tinygo --http_server -v 0.1.0

Successfully signed build/echo_tinygo_s.wasm with capabilities: wasmcloud:httpserver
```

I think that would be less confusing for the developer experience if the error were reported earlier in the toolchain.
