### ISSUE TITLE
[BUG] Cannot start providers 

### ISSUE THREAD

**Issue by Taction** [wasmCloud/wasmcloud-otp#437]
**Describe the bug**

Follow the tutorial Creating capability providers and successful [Creating a provider archive](https://wasmcloud.dev/app-dev/create-provider/create-par/). Then use the dashboard to start the provider, but failed both form file(build/fakepay_provider.par.gz) and registry. And here is the output of `make push`:
```
$ make push
wash reg push --insecure serverofmyself:5000/fakepay_provider:0.1.0 build/fakepay_provider.par.gz

🚿 Successfully validated and pushed to serverofmyself:5000/fakepay_provider:0.1.0
```

**To Reproduce**

follow https://wasmcloud.dev/app-dev/create-provider/

**Expected behavior**

Provider starts successfully.

**Environment (please complete the following information)**
wasmcloud-host:
 - OS:  Linux
 - Arch: x86_64
 - wasmCloud Version: build from master

compiling provider:
 - OS:   MacOS
 - Arch: x86_64

If you ran into this issue while developing a feature for wasmCloud:
 - Output of `elixir --version` e.g.:
 ```
Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.13.0 (compiled with Erlang/OTP 24)
 ```
 - Output of `cargo --version` e.g.:
 ```
cargo 1.62.0 (a748cf5a3 2022-06-08)
 ```

**Log info**
```
[info] JOINED lvu:1 in 2ms
  Parameters: %{"token" => "***"}
span_id=4eae22697f7fe699 trace_id=7de8620415b0ac729b113112b071efbb [error] Error starting provider from file: Not enough files found in provider archive. Is this a complete archive?

[debug] Received control interface request on wasmbus.ctl.default.cmd.NAWSOI5O2Q3OS66C5OPW5YKUT56UOOJCZVNORPDCS765ZPJFQA5E5D24.lp
[debug] StateMonitor handle info wasmbus.evt.default
[debug] Handling host heartbeat
span_id=c998f569ee7d57e0 trace_id=e2fcfd9cec2e39201629516f24854fb4 [error] Error starting provider from OCI: Not enough files found in provider archive. Is this a complete archive?
[debug] StateMonitor handle info wasmbus.evt.default
[debug] Event (com.wasmcloud.lattice.provider_start_failed) received but was ignored: No handler defined
```

**Additional context**

here is my provider: https://github.com/Taction/wasmcloud-payment-example/tree/main/fakepay-provider

**Comment by autodidaddict** [comment]
The error message in the logs gives us a hint. It looks like it's trying to open a .par.gz file for the provider and it can't.

Are you trying to start the binary directly? 
If you're starting the par, do you get any errors when running the make command to generate the par?

**Comment by brooksmtownsend** [comment]
I think the issue here may also be that you're on Mac and compiling a provider for Linux, would you mind sharing the output of "wash par inspect" when you give it both the OCI reference for your server and the local .par.gz file under build?

**Comment by Taction** [comment]
@autodidaddict @brooksmtownsend Thanks for the reply! 
I rebuild the provider on Linux, and it starts as expected!!!
This is the result of running the command `wash par inspect` on the previous .par.gz file:
```
                          fakepay-provider - Provider Archive                         
  Account                   ADCQBBHPM7I4QXNYRG462NXZ7WZSNSHYEN2DAZ6MRSRXY7KVPTLCFBTP  
  Service                   VC67TQ7H6UCMKWVUPZTBQJVO2LSVDQPNKKWWVJKPPOM6ORZO4BM5CUF4  
  Capability Contract ID                                  wasmcloud:example:payments  
  Vendor                                                                        Acme  
  Version                                                                      0.1.0  
  Revision                                                                         0  
Supported Architecture Targets                           x86_64-macos                                                                        
```

**Comment by brooksmtownsend** [comment]
Glad that worked @Taction !
