### ISSUE TITLE
[BUG] make release-prod can not work properly

### ISSUE THREAD

**Issue by Taction** [wasmCloud/wasmcloud-otp#444]
**Describe the bug**

When running `make release-prod` I encountered the following error:
```
==> Copying applications to _build/release_prod/rel/wasmcloud_host
==> Generating start_erl.data
==> Generating vm.args from rel/vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 13.0.1 from /usr/lib/erlang/erts-13.0.1
==> Generating boot scripts
==> Generating RELEASES
==> Release failed: no match of right hand side value: {:error, :eacces}
    (distillery 2.1.1) lib/distillery/releases/assembler.ex:863: Distillery.Releases.Assembler.create_RELEASES/2
    (distillery 2.1.1) lib/distillery/releases/assembler.ex:290: Distillery.Releases.Assembler.write_release_scripts/1
    (distillery 2.1.1) lib/distillery/releases/assembler.ex:50: Distillery.Releases.Assembler.assemble/1
    (distillery 2.1.1) lib/distillery/tasks/release.ex:130: Mix.Tasks.Distillery.Release.do_release/2
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.13.0) src/elixir_compiler.erl:73: :elixir_compiler.dispatch/4
    (elixir 1.13.0) src/elixir_compiler.erl:58: :elixir_compiler.compile/3

make: *** [Makefile:47: release-prod] Error 1
```

**To Reproduce**

1. Run command 'cd wasmcloud_host'
1. Run other command 'make release-prod'
1. See error

**Expected behavior**

**Environment (please complete the following information)**
 - OS:Linux
 - Arch: x86_64
 - wasmCloud Version: master branch

If you ran into this issue while developing a feature for wasmCloud:
 - Output of `elixir --version` e.g.:
 ```
Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.13.0 (compiled with Erlang/OTP 24)
 ```
 - Output of `cargo --version` e.g.:
 ```
cargo 1.62.0 (a748cf5a3 2022-06-08)
 ```

**Additional context**

The makefile seems to have some typo error, and I changed it to the following:
```
release-prod: build
	cd ../host_core && make copy-nif
	cd ../wasmcloud_host
	MIX_ENV=release_prod SECRET_KEY_BASE=$(SECRET_KEY_BASE) mix distillery.release --executable --verbose
```

**Comment by brooksmtownsend** [comment]
Thanks for submitting this @Taction, unfortunately OTP 25 is not supported by distillery https://github.com/bitwalker/distillery/issues/744 and we'll likely move to [mix releases](https://hexdocs.pm/mix/Mix.Tasks.Release.html) as a way to compensate. Distillery has gradually become less maintained as the official tooling caught up to its revolutionary features.

If you'd like to try, I'd be curious if this occurs for you with OTP 24, but if not I'd love to learn about your use case for building a release manually and see if I can help

**Comment by Taction** [comment]
@brooksmtownsend  Thanks for your reply. I am kindly new to the elixir, and I failed to downgrade the OTP to 24. 😭 

> I'd love to learn about your use case for building a release manually and see if I can help.

I would like to build my own image for I may change the source code. But since I am in china so there are some network issues with the command `make build-image`. so I want to build on my local machine instead of using docker, change the dockerfile to just copy the files.

**Comment by brooksmtownsend** [comment]
@Taction If you're looking to contribute, that's fantastic! If you'd like to build on your local machine, you can use the Elixir toolchain to do so. Check out https://github.com/wasmCloud/wasmcloud-otp/tree/main/wasmcloud_host#starting-the-host-and-web-ui-dashboard for instructions there 😄 

Let me know how these steps work for you, it's a great call-to-action for us to add

**Comment by Taction** [comment]
> @Taction If you're looking to contribute, that's fantastic! If you'd like to build on your local machine, you can use the Elixir toolchain to do so. Check out https://github.com/wasmCloud/wasmcloud-otp/tree/main/wasmcloud_host#starting-the-host-and-web-ui-dashboard for instructions there 😄
> 
> Let me know how these steps work for you! I'll take a look at the release prod script in the meantime

I can start successfully with `mix phx.server` command. Our team wants to build a test environment running on k8s, so we are finding a way to create an image, looking forward to solving the release prod script.

Also, is it possible to move `build esbuild` steps into dockerfile? In this way when running `build-arm-image` all steps will be running inside docker otherwise the host machine should also have the mix enviroment.

**Comment by brooksmtownsend** [comment]
> I can start successfully with mix phx.server command. Our team wants to build a test environment running on k8s, so we are finding a way to create an image, looking forward to solving the release prod script.

@Taction I did just want to point you to https://hub.docker.com/r/wasmcloud/wasmcloud_host, we publish a docker image with each release so you should be able to use that for your k8s test environment. However, if you're looking to contribute your own changes _and_ test for k8s, I would recommend using the `make build-image` or `make build-arm-image` targets instead, the `release_prod` target is a little more purpose built for our CI.

> Also, is it possible to move build esbuild steps into dockerfile? In this way when running build-arm-image all steps will be running inside docker otherwise the host machine should also have the mix enviroment.

Unfortunately the [dart_sass](https://github.com/CargoSense/dart_sass) package doesn't have support for aarch64-unknown-linux-gnu so it's not possible to build it into the Docker image 😢. That being said, the only time the static assets need to be updated are when there are CSS/JS changes, so we could explore committing those files. I'm also open to changing the tooling to a different bundler if that is available

**Comment by Taction** [comment]
@brooksmtownsend Thanks for your reply. We would like to test it in k8s if the changes work correctly. Waiting for the official image to be released is a bit slow behind and some of the custom modifications are not always accepted.

I've tried `make build-image` with 
```
$ elixir --version
Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]

Elixir 1.12.2 (compiled with Erlang/OTP 22)
```
and getting error:
```
mix compile
==> host_core
warning: the dependency :host_core requires Elixir "~> 1.13" but you are running on v1.12.2
mix sass default assets/css/app.scss priv/static/assets/app.css
==> host_core
warning: the dependency :host_core requires Elixir "~> 1.13" but you are running on v1.12.2
mix assets.deploy
==> host_core
warning: the dependency :host_core requires Elixir "~> 1.13" but you are running on v1.12.2

  ../priv/static/assets/app.js  216.2kb

⚡ Done in 87ms
==> wasmcloud_host
Check your digested files at "priv/static"
cp -r assets/static/* priv/static/
cp -r assets/css/coreui priv/static/assets/coreui
warning: the dependency :host_core requires Elixir "~> 1.13" but you are running on v1.12.2
cd ../ && \
docker build --build-arg APP_NAME=`grep 'app:' ./wasmcloud_host/mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g'` --build-arg APP_VSN=`grep '@app_vsn ' ./wasmcloud_host/mix.exs | cut -d '"' -f2` --build-arg SECRET_KEY_BASE===> host_core ==> wasmcloud_host ovbExehXOWbwbPjdzPyoVhPxm6jM6pTH2HrvlEMbX8mtwhD0JZAiE2+sL7Ze+Wt8 --build-arg SKIP_PHOENIX=false \
	--build-arg BUILDER_IMAGE=elixir:1.13.3-slim \
	--build-arg RELEASE_IMAGE=debian:bullseye-slim  \
	-t `grep 'app:' ./wasmcloud_host/mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g'`:`grep '@app_vsn ' ./wasmcloud_host/mix.exs | cut -d '"' -f2`-`git rev-parse --short HEAD` -t `grep 'app:' ./wasmcloud_host/mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g'`:latest \
	-f ./wasmcloud_host/Dockerfile \
	.
/bin/sh: 2: cannot create host_core: Is a directory
make: *** [Makefile:21: build-image] Error 2
```

**Comment by brooksmtownsend** [comment]
Closing as the new make targets like `make build-image` fixes this
