### ISSUE TITLE
Capture metrics in web dashboard

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#45]
Erlang has system APIs that allow for capturing metrics, these can be integrated into the web dashboard widgets to provide pretty usage statistics like uptime, memory usage, process count, etc.

Here are some of those APIs:
http://erlang.org/documentation/doc-5.7.4/erts-5.7.4/doc/html/erlang.html#erlang:system_info-1

http://erlang.org/doc/man/erlang.html#statistics-1

http://erlang.org/doc/man/erlang.html#memory-0

**Comment by autodidaddict** [comment]
@brooksmtownsend has already added a preliminary set of metrics like uptime and process count. Anything beyond that is out of scope for 0.50 and we should consider separately as enhancements.
