### ISSUE TITLE
[FEATURE] Refactor `host_call` to use `with` syntax

### ISSUE THREAD

**Issue by mattwilkinsonn** [wasmCloud/wasmcloud-otp#461]
**Is your feature request related to a problem? Please describe.**
Currently `host_call` uses a [long pipe statement](https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/web_assembly/imports.ex#L158-L177) to call `identify_target`, `verify_link`, `authorize_call`, and `invoke`. This works, but relies heavily on multiple dispatch to deal with various error states.

**Describe the solution you'd like**
Convert this pipe into a `with` statement. This was done for `identify_target` in #460, but we want to convert the entire pipe into this syntax. This will allow us to handle error states easier without creating many different variants of the same function.

**Describe alternatives you've considered**
The other option is keeping the pipe as-is, but I think changing this will help reduce the complexity of the code and allow for better error messages when things go wrong.

**Comment by brooksmtownsend** [comment]
Changed in #503
