### ISSUE TITLE
[Question] Are there any providers implemented in go?

### ISSUE THREAD

**Issue by Taction** [wasmCloud/wasmcloud-otp#472]
**Describe the Question**

Are there any examples or tutorials for implementing a provider in go?

I noticed that wasmcloud supports go, and there are tinygo SDKs in the https://github.com/wasmCloud/interfaces. For rust it uses [wasmbus-rpc](https://docs.rs/wasmbus-rpc), is there a similar library for go?

Any help will be appreciated.

**Comment by brooksmtownsend** [comment]
Hey @Taction , @jordan-rash has been pioneering the Go SDK for writing capability providers in Go 😄 The [litestream provider](https://github.com/jordan-rash/litestream-provider) is an example of this, and he's currently touching up a lot of the wasmcloud-go libraries.

Jordan can comment on if it's ready or not to experiment with!

**Comment by jordan-rash** [comment]
Hi @Taction ..... there are some experimental Go providers out there right now.  The current status is that @stevelr and I are in the process of finalizing the first pass of the SDKs.  There are quiet a few PRs out there for the work, but here is the [best tracker](https://github.com/wasmCloud/actor-tinygo/pull/9#issuecomment-1251138502).  As soon as we get the code generation caught up, this should be ready to test.  I would suspect by this time next week.

**Comment by Taction** [comment]
Awesome! Thanks for all your replies, and looking forward to that feature.

**Comment by jordan-rash** [comment]
No worries!  I will ping you here once the code gen and SDKs are in sync...give me until the end of next week :-)

**Comment by brooksmtownsend** [comment]
Closing this since we do have a few and there's not too much more to be said here 😄
