### ISSUE TITLE
[BUG]  Provider delete on a host deletes all providers with the same link name in lattice

### ISSUE THREAD

**Issue by izchethan** [wasmCloud/wasmcloud-otp#479]
**Describe the bug**

Deploy provider with same link name on more than one host of the cluster. Deleting any one provider will delete all the provider instances with same link name.

**To Reproduce**

1. We created a cluster of 2 wasmcloud hosts (with cluster of nats as a backend) - UI shows everything is up and configurations look great.
2. Deployed simple echo on one node and HTTP server on both the nodes, add link definition on one of the nodes - we are able to access echo on both nodes (link definition shows up on both nodes) - which is great.
3. We try to delete the HTTP server provider on one of the nodes (tried both by CLI and from the UI) - HTTP Server provider gets deleted from all nodes of the cluster! - This part is confusing since we tried to delete only from the one host and not from all!

Link name is the same on all nodes of the cluster for the provider.

**Expected behavior**
Provider deleted on only the specified host.

**Environment (please complete the following information)**
 - OS: Tried on both Linux and windows
 - Arch: Docker
 - wasmCloud Version: latest

**Comment by brooksmtownsend** [comment]
Fixed with #494
