### ISSUE TITLE
[BUG] host_config.json writes out to the current directory, not where the release is installed

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#480]
**Describe the bug**

Before mix releases, the `host_config.json` file would write to the directory where the release is installed. Now, it's written wherever your `$(PWD)` reports when you run `./bin/wasmcloud_host start` or `wash up`. This results in JSON configuration files strewn about in the filesystem. This is especially frustrating with git since these files can alter host behavior and shouldn't be committed alongside other changes.

**To Reproduce**

1. Start host
2. See host_config.json

**Expected behavior**

I expect the `host_config.json` file to write out where the host release is unpacked, or with a configurable environment variable (perhaps an optional variable to avoid writing the file at all would be useful too)

**Environment (please complete the following information)**
 - OS: [e.g. Linux, MacOS, Windows] Linux/Macos, not tested on Windows
 - Arch: [e.g. x86_64, aarch64] aarch64
 - wasmCloud Version: [e.g. 0.51.0] 0.57.0+

**Comment by giusdp** [comment]
Hi, I was checking out the good first issues to get familiar with the codebase. Can I take hold of this one? 

After a quick look, I think the culprit is line 225 in host_core.ex, it seems like there is a double write_json. One in the current directory and one for `.wash/host_config.json`


```elixir
  defp write_config(config) do
    write_json(config, @host_config_file)   <--- This must be writing in $(pwd)

    case System.user_home() do
      nil ->
        Logger.warn(
          "Can't write ~/.wash/#{@host_config_file}: could not determine user's home directory."
        )

      h ->
        write_json(config, Path.join([h, "/.wash/", @host_config_file]))
    end
  end
```
