### ISSUE TITLE
[Incorrect doc information?] Call alias can not contains Charatar `.`

### ISSUE THREAD

**Issue by Taction** [wasmCloud/wasmcloud-otp#488]
**Describe the bug**

According to doc [Actor to actor calls](https://wasmcloud.dev/app-dev/a2a/) in the Call alias section:
`This alias must be an alphanumeric string that can optionally have separator/hierarchy characters like . or / or _, e.g. accounting or accounting/invest.`

But the code only accept `/` or `_`: https://github.com/wasmCloud/wash/blob/main/src/claims.rs#L847

**Expected behavior**

I am not sure this is a bug for the code or for the doc. But needed to be corrected.

**Comment by Taction** [comment]
This is more like a documentation error, considering the error description:
```
Call alias contained invalid characters.
Valid aliases are lowercase alphanumeric and can contain underscores and slashes
```

**Comment by autodidaddict** [comment]
Yep the docs are incorrect here. Thanks for filing this issue

**Comment by brooksmtownsend** [comment]
Fixed in https://github.com/wasmCloud/wasmcloud-dev-site/pull/166 😄 Thanks @Taction
