### ISSUE TITLE
NIF needs to support multiple lattices

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#505]
Once the virtual host work and supervision tree refactoring is completed and merged from #503 , we will need to modify some of the core NIF functionality to support multiple lattices, including (but not limited to):
* Multiple chunking stores, one per lattice
* prevention of host binary caches from overlapping (e.g. isolate downloads)
* chunking/dechunking using the appropriate store
* misc host/lattice isolation as necessary

**Comment by brooksmtownsend** [comment]
@autodidaddict in the meantime, is there any action required for people who are using the host before this issue is addressed?

**Comment by autodidaddict** [comment]
No action required atm. This should have zero impact because there's no way to start a second virtual host inside the main OTP process unless you're in `iex`. The existence of multiple virtual hosts on different lattices is the only way to trigger the edge case this issue covers.

This issue will need to be implemented at the same time or before a feature is added that makes adding additional virtual hosts a first-class feature.
