### ISSUE TITLE
Shrink heartbeat output so individual instance IDs are not listed for actors

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#508]
For large or excessive numbers of actors in a given virtual host, the heartbeat size can become cumbersome, large, and occasionally even large enough to exceed the NATS default message size limit. One method for remediating this is to return an instance _count_ with the actor rather than an itemization of each instance. If a consumer needs an itemized listing, they can obtain it with a "host inventory" call.

Mentioned in #503

**Comment by brooksmtownsend** [comment]
Think we did this right @autodidaddict ?

**Comment by autodidaddict** [comment]
Yep new heartbeat format was one of the many changes in 0.60
