### ISSUE TITLE
[FEATURE] Change Inbox Prefix for Healthchecks

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wasmcloud-otp#517]
**Is your feature request related to a problem? Please describe.**
I would like to be able to pull out the healthcheck responses, but currently, they are random `_INBOX.uuid` topic names

**Describe the solution you'd like**
I would like to utilize the [custom inbox prefix](https://docs.rs/async-nats/latest/async_nats/struct.ConnectOptions.html#method.custom_inbox_prefix) functionality to make it easier to subscribe to just healthcheck responses.

**Describe alternatives you've considered**
I have tried to script out listening to the requests and then picking up the responses...i didn't like it.

I am happy to take a wack at this if someone can point me at the right section of code and there is a consensus on what the prefix should be

**Comment by jordan-rash** [comment]
Pictures!

<img width="947" alt="Screenshot 2022-12-13 at 7 36 45 AM" src="https://user-images.githubusercontent.com/15827604/207362222-af6c0c4f-145c-4626-b1e1-886a55bfa10a.png">

**Comment by brooksmtownsend** [comment]
🤔 Aren't these inbox prefixes just used when something else does a `nats req`? And for your use case, you're just looking to hook into each health check so you can monitor the health of the components, right?

**Comment by autodidaddict** [comment]
>I would like to be able to pull out the healthcheck responses, but currently, they are random _INBOX.uuid topic names

Snooping on other requester's `_INBOX` topics is in most cases, a security violation for a number of reasons. In most production scenarios, users are configured to be unable to listen on other people's reply topics. If you want to monitor the health of things from somewhere else, you can watch the events on the `wasmbus.evt.xxx` topic. 

If you think additional events should be published on that stream, then I think that's probably a better place to put what you need to observe.

**Comment by autodidaddict** [comment]
Also, as Brooks indicated, the custom inbox prefix in the Rust crate (and Go library) are only for setting the reply-to field when making requests, not for listening to responses from other user's requests.

**Comment by jordan-rash** [comment]
I acknowledge it wasn't the intended use of the prefix, but I guess I was trying to identify a way to hook into the health check message.

From monitoring the nats traffic via `nats sub ">"` (which should grab everything), after the initial `health_check_passed` message, I don't see anything from the providers in `wasmbus.evt....`, am I missing something?

**Comment by autodidaddict** [comment]
This is what I was getting at. We could make it so that the host itself emits an event when a provider changes health status. It doesn't do this today

**Comment by jordan-rash** [comment]
Ohhhh, yes, that would be super nifty :-)

**Comment by jordan-rash** [comment]
Admittedly, I am trying to hijack the healthcheck message (not so much the healthy=true/false) for observability reasons.  Its probably the wrong place to do it, i just noticed the field goes more or less unused

**Comment by jordan-rash** [comment]
Closing in favor of #519
