### ISSUE TITLE
[BUG] Providers built using recent glibc do not run on the wasmcloud/wasmcloud_host docker image

### ISSUE THREAD

**Issue by ceejimus** [wasmCloud/wasmcloud-otp#526]
**Describe the bug**

Providers built using recent rust toolchain do not run in the wasmcloud_host docker container. 

Whenever the provider is started, the host produces the following log messages:

```
wasmcloud-wasmcloud-1  | /tmp/wasmcloudcache/***/1673310670/wasmcloud_examples_payments_default: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/wasmcloudcache/***/1673310670/wasmcloud_examples_payments_default)
wasmcloud-wasmcloud-1  | /tmp/wasmcloudcache/***/1673310670/wasmcloud_examples_payments_default: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/wasmcloudcache/***/1673310670/wasmcloud_examples_payments_default)
wasmcloud-wasmcloud-1  | /tmp/wasmcloudcache/***/1673310670/wasmcloud_examples_payments_default: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/wasmcloudcache/***/1673310670/wasmcloud_examples_payments_default)
```

Discussions with @brooksmtownsend lead me to believe the base image for the container has an incompatible (outdated) glibc version than my own.

We think the image would have to be updated to accommodate recent glibc versions.

**To Reproduce**

1. Install recent rust toolchain and dependencies (I imagine this will install glibc if not present)
1. Build a rust provider (I built the provider as specified in the [tutorial docs](https://wasmcloud.com/docs/app-dev/create-provider/rust))
1. Start wasmcloud host
1. Start the provider

**Expected behavior**

The provider should successfully start on the host.

**Environment (please complete the following information)**

Host:
 - OS: Linux, Ubuntu 22.04.1 LTS (jammmy)
 - Arch: x86_64
 - cargo version `cargo 1.65.0 (4bc8f24d3 2022-10-20)`

Output from my machine:
```
% ldd --version                                                                                                                                                            23-01-11 - 15:39:36
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

 Docker:
 - wasmCloud Version: 0.59.0 (based on `/opt/app/bin/wasmcloud_host version` run in container)
 - base image: alpine:3.16 (based on the `build-image` command in the [makefile](https://github.com/wasmCloud/wasmcloud-otp/blob/8d7192ad076dec992d54d98546847ab4a52729b5/host_core/Makefile))

Output from alpine:3.16
```
/ # ldd --version
musl libc (x86_64)
Version 1.2.3
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
```

**Additional context**

I'm running a slightly modified version of the [docker-compose.yml](https://github.com/wasmCloud/examples/blob/main/docker/docker-compose.yml) from the examples repo. I've just added `WASMCLOUD_OCI_ALLOWED_INSECURE: registry:5000` to the environment section of the wasmcloud service. I'm then using insecure push to the registry using `make push` and then manually calling `wash ctl start provider`.

**Comment by brooksmtownsend** [comment]
Just an additional point, the `wasmcloud_host` image that we distribute actually works off of `debian:bullseye-slim`, the `host_core` image was an experiment to try alpine https://github.com/wasmCloud/wasmcloud-otp/blob/8d7192ad076dec992d54d98546847ab4a52729b5/wasmcloud_host/Makefile#L33

From that image, we have
```
root@6fd0e446ab25:/# ldd --version
ldd (Debian GLIBC 2.31-13+deb11u5) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by brooksmtownsend** [comment]
We're a little constrained here since we build off of the Elixir docker image, which builds off the Erlang docker image, and that base container is what we use to distribute. As you can see for `erlang:25`, the base image is bullseye https://github.com/erlang/docker-erlang-otp/blob/e9ce9f226c50a8cf186258d9f571f24dd4096bbf/25/slim/Dockerfile. I don't see a reason why we couldn't upgrade our release image to `debian:bookworm-slim`, we would just have to try it and make sure providers and the host still works. 

On bookworm-slim:
```
root@a27fb4e01eef:/# ldd --version
ldd (Debian GLIBC 2.36-7) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by brooksmtownsend** [comment]
Always possible #413 bites us as well if we try to upgrade

**Comment by brooksmtownsend** [comment]
@ceejimus I think we might be able to upgrade our base docker image from bullseye to bookworm now that we have more statically-linked ERTS 🤔 Do you have thoughts here around upgrading so we can support newer built providers?

**Comment by ceejimus** [comment]
> @ceejimus I think we might be able to upgrade our base docker image from bullseye to bookworm now that we have more statically-linked ERTS thinking Do you have thoughts here around upgrading so we can support newer built providers?

My Erlang/Elixer experience is basically nil, so I'll just defer to you on this one :)
