### ISSUE TITLE
[FEATURE] Host version in logs

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wasmcloud-otp#540]
**Describe the solution you'd like**
Would it be possible to add the version to the end of this log line 
`20:19:06.763 [info] Started wasmCloud OTP Host Runtime - vX.Y.Z`

**Describe alternatives you've considered**
Unless I am very dense, I dont see the version in the logs

**Comment by thomastaylor312** [comment]
It should be [in there](https://github.com/wasmCloud/wasmcloud-otp/blob/7a436f03fad34d54be41ca511e01d2fbf18a11eb/host_core/lib/application.ex#LL66C5-L69C6), but I think that @autodidaddict mentioned something about how it might not be printing with this?

**Comment by autodidaddict** [comment]
This prints on the version I'm running, but that's 0.60

**Comment by jordan-rash** [comment]
sorry @connorsmith256, i thought it would be a simple ask :-(

I dont need it that bad, so dont spin your wheels....I can also just put structured_logging on.

**Comment by connorsmith256** [comment]
@jordan-rash no problem! It wasn't too difficult, and this has been bugging me for a bit :)
