### ISSUE TITLE
[FEATURE] Support optional `correlation_id` on control interface requests

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#618]
**Is your feature request related to a problem? Please describe.**
Interacting with the wasmCloud host is almost always done through the control interface. Whether it's `wash`, the lattice controller, or just publishing on the right NATS topic, these commands are how the host can be told to start/stop actors, providers, link them, etc.

When it comes to knowing what happened in response to a command, you can either:
1. Wait for a synchronous reply from the host telling you what it did, but all commands are designed to "ack" rather than confirm the completion of work
2. Wait for an event describing what happened (subscribe to `wasmbus.evt.>` and wait for `provider_started`).

When choosing option 2, there's no real way to know that an event happened in response to **your** command. For example, if two different control clients publish a command to start the same actor, you would see two `actor_started` event but not know which one corresponded to your request. This can be especially problematic when considering [wadm](https://github.com/wasmCloud/wadm), which will often ask for many actors to be started.

**Describe the solution you'd like**
A simple way to do this, as suggested by @autodidaddict, is to support "correlation IDs". Effectively, each command that comes in through the control interface could include a unique (up to the client to determine this) identifier for a command, and every event that is published in response to that command will also include the same correlation ID. In practice, a time-sortable unique ID would be most useful here.

**Describe alternatives you've considered**
We've attempted, and mostly completed, a prototype of **wadm** that uses just annotations in order to uniquely identify events. However, there still cases where this isn't sufficient, especially when starting 10000 actors. It's very difficult to put a time frame on how long this _should_ take to complete, so this PR is most useful when combined with #617.

**Comment by liamwh** [comment]
I'm new here and no elixir dev, so am uncertain if the commands are CloudEvents, but if they are, and we want to embed something for tracing into the control interfaces commands, is it an idea that we follow the [CloudEvents distributed tracing spec](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md) and add a [traceparent attribute](https://w3c.github.io/trace-context/#traceparent-header)?

**Comment by brooksmtownsend** [comment]
@liamwh Great question, the commands themselves are not CloudEvents but the resulting events are. We could certainly follow that idea and add NATS headers (the project we use to send messages), since the control interface works with those 🤔

**Comment by liamwh** [comment]
@brooksmtownsend Nice thinking! 2 remarks:

1. I'm not sure if OpenTelemetry is relevant to the commands, but if it is and you want to put in a traceparent header into the NATS headers, then perhaps this Rust code helps serve as a reference how to get a traceparent header together from a current span for anyone looking into this issue:
    
    For the below example OpenTelemetry is set up as seen [in this gist](https://gist.github.com/liamwh/48cdd67f296a88a20ec924856302f073), and the code is executed inside an open span.
    
    ```rs
      let span = tracing::Span::current();
      let otel_context = span.context();
      let span = otel_context.span();
      let span_context = span.span_context();
      if span_context.is_sampled() {
          let trace_id = span_context.trace_id().to_bytes();
          let span_id = span_context.span_id().to_bytes();
          let trace_flags = span_context.trace_flags().to_u8();
          let trace_id_hex = hex::encode(trace_id);
          let span_id_hex = hex::encode(span_id);
          let traceparent = format!("00-{}-{}-{:02x}", trace_id_hex, span_id_hex, trace_flags);
      }
      ```
      
2. I noticed you mentioned desiring a time-sortable unique ID here. I know of just the thing: the successor to UUIDs, the [ULID](https://github.com/ulid/spec). Perhaps [this](https://github.com/TheRealReal/ecto-ulid) is useful?
