### ISSUE TITLE
[FEATURE] release smoke test++

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmcloud-otp#619]
**Is your feature request related to a problem? Please describe.**
In https://github.com/wasmCloud/wasmcloud-otp/pull/616 a simple smoke test was added for releases executing the binary on all runners and simply killing it after a timeout to ensure it did not crash. Would be great to extend it a bit and rather than just killing after timeout, perhaps do some `curl` calls to the API and/or fetch wash binary and use wash to interact with the server

**Describe the solution you'd like**
`curl` it or `wash` it, whatever we do, it should be fast, i.e. 1 minute is the top threshold of how long this whole process can take per binary

**Comment by brooksmtownsend** [comment]
I like the idea of `curl`ing the dashboard to ensure a response, and then using `wash` to query the inventory of the host or start a really small actor.
