### ISSUE TITLE
[FEATURE] rename label syntax from `HOST_` to `WASMCLOUD_HOST_`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#637]
**Is your feature request related to a problem? Please describe.**
As @jordan-rash pointed out, the `HOST_<label>=<value>` environment variable syntax is likely to run into a few other tools' configuration. At least for nix users, the `HOST_PATH` variable is used often to link to binaries that nix needs to resolve. This can lead to cumbersome labels for hosts, so it would be better to prefix this environment variable like our others.

**Describe the solution you'd like**
Instead of looking for environment variables with `HOST_` as a prefix, look for `WASMCLOUD_HOST_` as a prefix.

**Describe alternatives you've considered**
We could leave it as-is, though this will require people who have predefined environments to either unset those variables, unset the variables in a sub-shell, or simply ignore the variables. This seems lazy 😉 

**Additional context**
We should consider the breaking change here where scripts and previous commands using `HOST_` won't work anymore. We can consider deprecation, but this wouldn't resolve the issue mentioned above.

**Comment by ricochet** [comment]
Good call out. I prefer all env vars to have the same prefix for systems that I use.

**Comment by jordan-rash** [comment]
Bad bot

**Comment by jordan-rash** [comment]
I HATE YOU BOT

**Comment by connorsmith256** [comment]
@jordan-rash I didn't fix it in the OTP host, but I did for the Rust host in https://github.com/wasmCloud/wasmCloud/pull/731 :)

**Comment by thomastaylor312** [comment]
OTP is deprecated and we did this in the rust host already! Closing
