### ISSUE TITLE
[BUG] starting a provider from file should work

### ISSUE THREAD

**Issue by pgray** [wasmCloud/wasmcloud-otp#639]
**Describe the bug**
The code for running a provider from a file exists at: https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/providers/provider_supervisor.ex#L30

but `wash ctl start provider file://$path-to-file` fails with "Invalid reference format"

**To Reproduce**

1. create a new provider
2. build it
3. `wash ctl start provider file://$PWD/build/provider.par.gz`

**Expected behavior**
The provider should load and start just like it does via web UI

**Environment (please complete the following information)**
 - OS: macOS
 - Arch: aarch64
 - wasmCloud Version: 0.63.1

**Additional context**
cc @aish-where-ya

**Comment by thomastaylor312** [comment]
Closed in #641
