### ISSUE TITLE
[BUG] In case of high concurrency, the actor is automatically deleted

### ISSUE THREAD

**Issue by Iceber** [wasmCloud/wasmcloud-otp#647]
**Describe the bug**
I started `wasmcloud.azurecr.io/echo:0.3.8` and `wasmcloud.azurecr.io/httpserver:0.17.0`, then used `siege` to pressure test the http service, and the actor is automatically cleaned up when i use higher concurrent requests.

This is a weird and magical issue.

**To Reproduce**

1. `wash up`
2. in dashboard, start actor `wasmcloud.azurecr.io/echo:0.3.8`, and scale to 50
3. in dashboard, start product `wasmcloud.azurecr.io/httpserver:0.17.0`
4. in dashboard, new link and listen 8080 port
5. use `siege -c 200 -r 100 http://127.0.0.1:8080`, It's not an immediate problem, so you can run it a few more times until the request keeps returning 500
6. return to the dashboard, you can see that actor is gone.

**Expected behavior**

I expect actor not to be deleted automatically.

**Environment (please complete the following information)**
 - OS: [e.g. Linux, MacOS, Windows] MacOS
 - Arch: [e.g. x86_64, aarch64] aarch64
 - wasmCloud Version: [e.g. 0.51.0] 0.63.1

If you ran into this issue while developing a feature for wasmCloud:
 - Output of `elixir --version` e.g.:
 ```
# use wash to start wasmcloud_host
wasmcloud_host_erts-13.2.1_0.63.1/erts-13.2.1
 ```
 - Output of `cargo --version` e.g.:
 ```
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
 ```

**Screenshots**

**Additional context**

There are a lot of errors like this in the logs, and this may be the key message
```
13210 ^M12:29:19.628 [error] Task #PID<0.5094.0> started from #PID<0.562.0> terminating
13211 ** (stop) exited in: GenServer.call(#PID<0.3402.0>, {:handle_incoming_rpc, %{body: <<136, 166, 111, 114, 105, 103, 105, 110, 131, 170, 112, 117, 98, 108, 105, 99, 95, 107, 101, 121, 217, 56, 86, 65, 71, 5      1, 81, 73, 84, 81, 81, 50, 79, 68, 65, 79, 87, 66, 53, 84, 84, 81, 83, 68, 74, 53, 51, ...>>, description: nil, gnat: #PID<0.330.0>, headers: [], reply_to: "_INBOX.vGqudpuHN9sDrrXwM6sZZD", sid: 10, status      : nil, topic: "wasmbus.rpc.default.MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5"}}, 5000)
13212     ** (EXIT) exited in: GenServer.call(#PID<0.334.0>, {:invoke_actor, %HostCore.WasmCloud.Runtime.ActorReference{resource: #Reference<0.1056116147.3308388354.63680>, reference: #Reference<0.1056116147.33      08257282.63681>}, "HttpServer.HandleRequest", <<133, 166, 109, 101, 116, 104, 111, 100, 163, 71, 69, 84, 164, 112, 97, 116, 104, 161, 47, 171, 113, 117, 101, 114, 121, 83, 116, 114, 105, 110, 103, 160, 16      6, 104, 101, 97, 100, 101, 114, 133, 170, 99, 111, 110, 110, 101, ...>>, <<131, 104, 9, 100, 0, 8, 115, 112, 97, 110, 95, 99, 116, 120, 110, 16, 0, 240, 177, 237, 53, 233, 85, 38, 103, 52, 194, 179, 240,       144, 238, 181, 162, 110, 8, 0, 77, 137, 206, 110, 2, 84, 171, 251, 97, ...>>}, 5000)
13213         ** (EXIT) time out
13214     (elixir 1.14.4) lib/gen_server.ex:1038: GenServer.call/3
13215     (host_core 0.63.1) lib/host_core/actors/actor_rpc_server.ex:52: HostCore.Actors.ActorRpcServer.request/1
13216     (gnat 1.6.0) lib/gnat/server.ex:62: Gnat.Server.execute/2
13217     (elixir 1.14.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
13218     (elixir 1.14.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
13219     (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
13220 Function: &Gnat.Server.execute/2
13221     Args: [HostCore.Actors.ActorRpcServer, %{body: <<136, 166, 111, 114, 105, 103, 105, 110, 131, 170, 112, 117, 98, 108, 105, 99, 95, 107, 101, 121, 217, 56, 86, 65, 71, 51, 81, 73, 84, 81, 81, 50, 79, 6      8, 65, 79, 87, 66, 53, 84, 84, 81, 83, 68, 74, 53, 51, ...>>, description: nil, gnat: #PID<0.330.0>, headers: [], reply_to: "_INBOX.vGqudpuHN9sDrrXwM6sZZD", sid: 10, status: nil, topic: "wasmbus.rpc.defau      lt.MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5"}]
13222 12:29:19.628 [error] Task #PID<0.5100.0> started from #PID<0.562.0> terminating
```

**Comment by thomastaylor312** [comment]
I'm really curious how this will perform on the rust host and if we can gain any insight there. This seems like an actor panic, but normally the actor gets restarted

**Comment by connorsmith256** [comment]
@brooksmtownsend would you mind copying your response from the wasmCloud slack here?

**Comment by brooksmtownsend** [comment]
I’m 80% sure that the issue that you’re hitting is one that’s unique to the way that NATS handles opening file descriptors on Mac. You actually end up running out of possible connections to open after approximately 16000 requests if I remember correctly. The other 20% there would most likely come down to the HTTPserver sending too many concurrent requests to actors that are busy handling a previous request, and if you exceed the 5 second timeout then the OTP process will restart.

**Comment by Iceber** [comment]
@brooksmtownsend Thanks, it looks like a reboot because the actor is gone, and it looks like only the actor part was rebooted, the provider is still in memory and it can be seen in the dashboard

**Comment by connorsmith256** [comment]
I think Brooks is right: when there are too many requests for the actor instances to manage, and the actor module supervisor takes 5+ seconds before responding, the OTP supervisor will restart the supervisor process. Providers shouldn't be affected by this
