### ISSUE TITLE
Possible race condition in provider shutdown logic

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmcloud-otp#87]
I'm not sure if this is a real race condition, but wanted to log this issue so we can come back to it.
https://github.com/wasmCloud/wasmcloud-otp/blob/7ddd377de8d11e9e3f60e543ed343ea22b9ec649/host_core/lib/host_core/providers/provider_supervisor.ex#L61

The sequence of operations is:
- host sends provider a shutdown message
- provider replies to host with ack
- host calls ProviderModule.Halt

NATS doesn't guarantee delivery order, for example including if retry is enabled.
The race condition scenario would be:
- provider sends message X (to actor or host)
- provider receives shutdown message and replies to it
- host receives shutdown ack and calls Halt
- host receives message X

I haven't dug into the implementation of Halt() so I don't what exactly happens in that scenario, but what _should_ happen is that the message X gets delivered.

Note that this can happen even if the provider does not send any messages after sending the shutdown ack - provider could have flushed all output buffers and exit immediately after sending. The problem arises because the message could still be in some NATS message queue or retry queue somewhere.

I suggest adding a delay of N seconds (configurable) between host receiving shutdown response and calling Halt.

**Comment by autodidaddict** [comment]
NATS doesn't have retry built-in, nor does it even have retry queues. Not in the mode / feature set we're using. If a message doesn't make it, that message is gone and will _not_ be re-attempted. We're using NATS in _at most_ once delivery.
