### ISSUE TITLE
Support manifest files in the web UI

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#9]
Allow someone to upload or paste a manifest file into a web UI and the web ui should then perform all of the loads and configurations as defined in the file.

**Comment by brooksmtownsend** [comment]
This issue will likely be easier once there's an officially supported way to do manifests in the OTP runtime, if manifests are only used as a tool for development in the dashboard then it will be more complicated

**Comment by brooksmtownsend** [comment]
This is probably better as a wadm manifest https://github.com/wasmCloud/wadm/tree/main/oam, and I think that support for this would likely overlap significantly with the goals of wadm
