### ISSUE TITLE
Enforce anti-forgery token rules on provider->actor invocations

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#99]
We currently do not enforce this because at the moment there are no providers currently sending anti-forgery tokens on the invocations. Once we have at least the HTTP server and the Redis key-value provider (the ones we use for our automated tests) sending AFTs, then we will need to enable AFT checking.

**Comment by stevelr** [comment]
If this is referring to signed Invocations, then both httpserver and kvredis are doing this. This should be ready to turn on in the host, @autodidaddict
